services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  backend-1:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      PORT: 4000
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost
    depends_on:
      - redis

  backend-2:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      PORT: 4000
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost
    depends_on:
      - redis

  score-worker:
    build:
      context: ./backend
    command: ["npm", "run", "worker:score"]
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        # Reemplazamos los marcadores por tus datos reales de Supabase
        NEXT_PUBLIC_SUPABASE_URL: "https://jcltornjvapftknookqc.supabase.co"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "TU_CLAVE_ANON_O_PUBLIC_REAL_DE_SUPABASE"
        NEXT_PUBLIC_API_URL: http://localhost/api
    environment:
      PORT: 3001
      NEXT_PUBLIC_API_URL: http://localhost/api
    depends_on:
      - backend-1
      - backend-2

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend-1
      - backend-2

volumes:
  redis-data:
