events {
    worker_connections 1024;
}

http {
    # 1. Definición del grupo de balanceo de carga (Upstream)
    upstream backend_servers {
        # Algoritmo por defecto: Round-Robin (un intento a cada uno)
        server backend-1:4000;
        server backend-2:4000;
    }

    server {
        listen 80;
        server_name localhost;

        # 2. Redirección del tráfico de la API al balanceador de carga
        location /api/ {
            proxy_pass http://backend_servers/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        # 3. Redirección de todo el resto del tráfico al Frontend (Next.js)
        location / {
            proxy_pass http://frontend:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}